# ===============================
# = H2 Database Config
# ===============================
spring.datasource.url=jdbc:h2:mem:meethivedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Auto-create/update tables
spring.jpa.hibernate.ddl-auto=update

# Show SQL in console (for learning)
spring.jpa.show-sql=true
